// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psqcbxrbueciotypecjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzcWNieHJidWVjaW90eXBlY2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzcyMTgsImV4cCI6MjA3NDA1MzIxOH0._9wdUiMjyQ_Y5sxPuE8vdw3-RRIBichGyGtBf5nex1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});